export const GroupActivityType = {
  POST_COLLAB_START: 'POST_COLLAB_START',
  POST_EDIT_START: 'POST_EDIT_START',
  POST_COLLAB_COMPLETE: 'POST_COLLAB_COMPLETE',
  POST_EDIT_COMPLETE: 'POST_EDIT_COMPLETE',
  POST_CREATE: 'POST_CREATE',
  POST_UPDATE: 'POST_UPDATE',
  POST_DELETE: 'POST_DELETE',
  MEMBER_JOIN: 'MEMBER_JOIN',
  MEMBER_LEAVE: 'MEMBER_LEAVE',
  MEMBER_REMOVE: 'MEMBER_REMOVE',
  MEMBER_ROLE_CHANGE: 'MEMBER_ROLE_CHANGE',
  GROUP_COVER_UPDATE: 'GROUP_COVER_UPDATE',
  GROUP_NAME_UPDATE: 'GROUP_NAME_UPDATE',
  MEMBER_NICKNAME_CHANGE: 'MEMBER_NICKNAME_CHANGE',
  GROUP_MONTH_COVER_UPDATE: 'GROUP_MONTH_COVER_UPDATE',
  GROUP_CREATE: 'GROUP_CREATE',
} as const;

export type GroupActivityType =
  (typeof GroupActivityType)[keyof typeof GroupActivityType];
